# Numpy

In [30]:
#Numpy
#Pandas
#Tensorflow

# Arrays
1. Faster
2. Contigous memory allocation
3. Same data type
4. If you want to increase size, recreate array
5.less memory
6.Array can manage arithmetic operations.
7.Array favors a Larger sequence of data.

List
1. Slow
2. Sparse memory
3. Different data types
4. Can dynamically grow
5.More memory
6.List cannot manage arithmetic operations.
7.List favors a shorter sequence of data.

In [2]:
#A comparison of numpy Vs. List in python

In [1]:
import numpy as np

In [7]:
python_list = range(1000000) # A list from 0 to 1000000

In [3]:
numpy_array = np.arange(1000000) # An array from 0 to 1000000

In [4]:
#Multiply a list with 5, 1000 times using list comprehension

In [5]:
%time for i in range(100): results = [i*5 for i in python_list]

CPU times: total: 9.23 s
Wall time: 9.3 s


In [ ]:
#Multiply numpy array with 5, 1000 times

In [9]:
%time for i in range(100): result = numpy_array * 5

Wall time: 372 ms


In [10]:
#Numpy array creation methods

In [19]:
one_d_array = np.zeros(10)
one_d_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
one_d_array = np.ones((10))
one_d_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
one_d_array*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [18]:
#Creating array of any number
x = np.zeros(10) 
x = x + 5
x

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [17]:
x= np.arange(1,11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
#Shape of array
x = np.zeros((3,2,5))
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [29]:
x.shape

(3, 2, 5)

In [31]:
#Array of custom elements

In [32]:
x = np.array([1,3,7,9,10,16,78,18])
x

array([ 1,  3,  7,  9, 10, 16, 78, 18])

In [33]:
x.shape

(8,)

In [35]:
y = x.reshape((2,4))

In [42]:
y

array([[ 1,  3,  7,  9],
       [10, 16, 78, 18]])

In [36]:
y.shape

(2, 4)

In [37]:
y.ndim

2

In [38]:
y

array([[ 1,  3,  7,  9],
       [10, 16, 78, 18]])

In [39]:
#Accessing individual elements of array

In [40]:
y[0,3]

9

In [41]:
y[1,2]

78

In [43]:
z = y.reshape((2,2,2))

In [44]:
z

array([[[ 1,  3],
        [ 7,  9]],

       [[10, 16],
        [78, 18]]])

In [45]:
z[0,1,1]

9

In [46]:
z.ndim

3

In [114]:
z.dtype

dtype('int32')

In [47]:
#Slicing

In [48]:
y

array([[ 1,  3,  7,  9],
       [10, 16, 78, 18]])

In [49]:
#Slicing : Start, end, step
y = y.reshape(4,2)

In [50]:
y

array([[ 1,  3],
       [ 7,  9],
       [10, 16],
       [78, 18]])

In [51]:
y[0:3]

array([[ 1,  3],
       [ 7,  9],
       [10, 16]])

In [52]:
y

array([[ 1,  3],
       [ 7,  9],
       [10, 16],
       [78, 18]])

In [63]:
y[0:3,1]

array([ 3,  9, 16])

In [54]:
y

array([[ 1,  3],
       [ 7,  9],
       [10, 16],
       [78, 18]])

In [55]:
y[::2]

array([[ 1,  3],
       [10, 16]])

In [56]:
y

array([[ 1,  3],
       [ 7,  9],
       [10, 16],
       [78, 18]])

In [57]:
y[::,0]

array([ 1,  7, 10, 78])

In [58]:
x

array([ 1,  3,  7,  9, 10, 16, 78, 18])

In [60]:
x[[3,5]] #Fancy indexing

array([ 9, 16])

In [64]:
#Vectorized operations

In [65]:
x = np.array([1,5,7])
y = np.array([3,2,9])

In [66]:
x+y

array([ 4,  7, 16])

In [67]:
x-y

array([-2,  3, -2])

In [68]:
x*y

array([ 3, 10, 63])

In [69]:
x/y

array([0.33333333, 2.5       , 0.77777778])

In [70]:
1/x

array([1.        , 0.2       , 0.14285714])

In [71]:
x*y**2

array([  9,  20, 567])

In [72]:
#Shapes

###### 00000
###### 11111
###### 11111
###### 11111
###### 00000

In [77]:
arr = np.ones((10,10))

In [78]:
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [79]:
arr[0] = 0
arr[-1] = 0

In [80]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

###### 00000
###### 01110
###### 01110
###### 01110
###### 00000

In [86]:
arr = np.zeros((5,5))

In [87]:
arr

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
arr[1:-1] = 1

In [89]:
arr

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 0., 0.]])

In [94]:
x = np.array([1,8,9,10,11])
            #0123456
            #-6-5-4-3-2-1

In [91]:
x[-1]

11

In [92]:
x[-2]

10

In [93]:
x[-3]

9

Assignment: Checkerboard pattern

# Football ground
#### 00000
#### 11111
#### 00000
#### 11111
#### 00000
#### 11111

# Cross pattern

### 01110
### 10101
### 11011
### 10101
### 01110

In [100]:
np.empty((9,9)) #Random/ arbitrary values

array([[1.06809792e-306, 1.37962456e-306, 1.69111861e-306,
        1.78020169e-306, 1.37961777e-306, 7.56599807e-307,
        1.41529388e+161, 2.78846014e-311, 4.52660420e+097],
       [7.72503545e-043, 3.41845526e+126, 7.56595733e-307,
        1.11256817e-306, 1.87600179e-311, 1.42417221e-306,
        1.11260619e-306, 8.90094053e-307, 1.86919378e-306],
       [1.06809792e-306, 1.37962456e-306, 1.69111861e-306,
        1.78020169e-306, 1.37961777e-306, 7.56599807e-307,
        6.19622771e-312, 3.33593535e-311, 6.23042070e-307],
       [4.67296746e-307, 1.69121096e-306, 7.56595733e-307,
        1.11256817e-306, 1.06811422e-306, 1.42417221e-306,
        1.11260619e-306, 8.90094053e-307, 1.86919378e-306],
       [1.06809792e-306, 1.37962456e-306, 1.69111861e-306,
        1.78020169e-306, 1.37961777e-306, 7.56599807e-307,
        4.66839075e-313, 3.80277782e-311, 6.23042070e-307],
       [4.67296746e-307, 1.69121096e-306, 7.56595733e-307,
        1.11256817e-306, 1.06811422e-306, 1.4241722

In [101]:
x

array([ 1,  8,  9, 10, 11])

In [102]:
x.dtype

dtype('int32')

In [103]:
#Comparion between metrices

In [106]:
salary = np.array([10, 25, 5, 2])

In [108]:
salary [salary > 5]

array([10, 25])

In [109]:
#Numpy element-wise functions

In [111]:
nums = [10,20,56,78,90]

In [112]:
np.sin(nums)

array([-0.54402111,  0.91294525, -0.521551  ,  0.51397846,  0.89399666])

In [113]:
np.sqrt(nums)

array([3.16227766, 4.47213595, 7.48331477, 8.83176087, 9.48683298])

In [115]:
#Assignment: Try all functions