In [1]:
import numpy as np
a=np.array([[3,4,2,5],[1,0,2,3],[5,3,4,5],[3,2,3,2]])
np.where(a>=5,66,33)

array([[33, 33, 33, 66],
       [33, 33, 33, 33],
       [66, 33, 33, 66],
       [33, 33, 33, 33]])

In [2]:
a.T

array([[3, 1, 5, 3],
       [4, 0, 3, 2],
       [2, 2, 4, 3],
       [5, 3, 5, 2]])

In [3]:
a.cumsum()

array([ 3,  7,  9, 14, 15, 15, 17, 20, 25, 28, 32, 37, 40, 42, 45, 47])

In [4]:
a.cumprod()

array([  3,  12,  24, 120, 120,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0])

In [5]:
a.mean()

2.9375

In [6]:
a.sum()

47

In [7]:
a

array([[3, 4, 2, 5],
       [1, 0, 2, 3],
       [5, 3, 4, 5],
       [3, 2, 3, 2]])

In [8]:
a.any()

True

In [9]:
a.all()

False

In [10]:
np.sort(a)

array([[2, 3, 4, 5],
       [0, 1, 2, 3],
       [3, 4, 5, 5],
       [2, 2, 3, 3]])

In [11]:
np.unique(a)

array([0, 1, 2, 3, 4, 5])

In [12]:
a

array([[3, 4, 2, 5],
       [1, 0, 2, 3],
       [5, 3, 4, 5],
       [3, 2, 3, 2]])

In [13]:
np.save('aa.npy',a)

In [14]:
o=np.load('aa.npy')
o

array([[3, 4, 2, 5],
       [1, 0, 2, 3],
       [5, 3, 4, 5],
       [3, 2, 3, 2]])

In [15]:
b=np.array([4,2,34,334,3453,5637])
b

array([   4,    2,   34,  334, 3453, 5637])

In [16]:
b

array([   4,    2,   34,  334, 3453, 5637])

In [17]:
np.savez('rr.npz',a,b)

In [18]:
i=np.load('rr.npz')

In [19]:
rr['b']

NameError: name 'rr' is not defined

In [250]:
a

array([[4, 3, 6],
       [3, 5, 3]])

In [251]:
a.diagonal()

array([4, 5])

In [282]:
linalg.det(a)

-62.00000000000001

In [277]:
from numpy import linalg
print(a)
linalg.inv(a)

[[ 3  2]
 [34  2]]


array([[-0.03225806,  0.03225806],
       [ 0.5483871 , -0.0483871 ]])

In [278]:
linalg.dot(a)

AttributeError: module 'numpy.linalg' has no attribute 'dot'

In [256]:
a

array([[4, 3, 6],
       [3, 5, 3]])

In [257]:
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [258]:
a

array([[4, 3, 6],
       [3, 5, 3]])

In [259]:
np.split(a,[1,3])

[array([[4, 3, 6]]), array([[3, 5, 3]]), array([], shape=(0, 3), dtype=int32)]

In [ ]:
#dir(np)

In [ ]:
np.split(a,[3,6])

In [ ]:
import numpy as np
b=np.array([3,56,5,45,456,45,7,97,6])
np.split(b,[2,4])

In [ ]:
a

In [ ]:
import numpy as np
a=np.array([[3,4,2,5],[1,0,2,3],[5,3,4,5],[3,2,3,2],[44,33,66,88],[1,2,53,8]])
a

In [ ]:
np.split(a,[1,3,5])

In [ ]:
a

In [ ]:
np.split(a,2,axis=1)

In [ ]:
daud=np.array([[343,654,2345,234],[765,36,3,8],[846,23,4,1]])
ali=np.array([[555,444,234,23],[42,634,2,1],[45,56,65,2]])
print(f'''
daud:    
      {daud}

ali:      
      {ali}

''')

In [ ]:
daud+ali

In [ ]:
np.concatenate((daud,ali))

In [20]:
np.concatenate((daud,ali),axis=1)

NameError: name 'daud' is not defined

In [21]:
np.hstack((daud,ali))

NameError: name 'daud' is not defined

In [22]:
np.vstack((daud,ali))

NameError: name 'daud' is not defined

In [23]:
np.r_[daud,ali]

NameError: name 'daud' is not defined

In [24]:
np.c_[daud,ali]

NameError: name 'daud' is not defined

In [25]:
shah=np.array([[7,90,6],[23,5323,4],[6,43,4]])

In [26]:
#np.c_[np.r_[daud,ali],shah]

In [27]:
e=np.random.seed(5)

In [28]:
np.random.randint(5,size)

NameError: name 'size' is not defined

In [ ]:
np.random.seed()

In [57]:
np.random.randint(6,9,size=(3,4))

array([[7, 7, 6, 8],
       [8, 8, 7, 8],
       [6, 7, 8, 7]])

In [55]:
np.random.randint(2,9)

8

In [60]:
np.random.gamma(2,9,size=(4,4))

array([[ 4.11400147, 34.54936205, 10.00927026,  4.76384112],
       [29.1280127 ,  7.29216089, 11.88737165,  7.96319226],
       [21.38179814, 19.18136203,  2.30490602, 30.25593528],
       [12.77272175, 12.9991346 , 19.34529735, 16.96337875]])

In [61]:
np.random.normal(4,8,size=(5,5))

array([[  5.47053696,  11.54135169,   7.01279432,  -1.05552112,
         -0.50453673],
       [ -5.57039935,  -5.64573634,   1.91132461,  -3.87791101,
          4.57298825],
       [ 11.77478704,   9.56423975,   7.45302574,  10.130908  ,
          5.75683564],
       [  6.66100818,   2.83667538,   4.71372506,   1.71104781,
         -0.13236587],
       [-12.1583415 ,   2.08905779,  -1.23814898,  17.92229886,
          3.11137835]])

In [99]:
np.random.randint(5.5,9.9,(6,6))


array([[7, 5, 6, 6, 6, 8],
       [5, 5, 6, 5, 8, 7],
       [8, 7, 6, 8, 5, 8],
       [5, 7, 8, 8, 5, 5],
       [7, 8, 7, 8, 7, 6],
       [5, 6, 5, 6, 7, 8]])

In [108]:
import numpy as np

# Set the seed to 42
np.random.seed(42)

# Generate a random array of shape (3, 2)
x = np.random.rand(3, 2)

print(x)

[[0.37454012 0.95071431]
 [0.73199394 0.59865848]
 [0.15601864 0.15599452]]


In [144]:
np.random.seed(2)
np.random.randint((3,8))
                  
                  

array([0, 7])

In [146]:
np.random.randint(3,7,(6,3))

array([[3, 5, 6],
       [5, 6, 3],
       [6, 5, 4],
       [6, 6, 4],
       [6, 6, 6],
       [5, 3, 3]])

In [147]:
from numpy import linalg

In [149]:
a=([4,3,442,8],[34,345,3],[645,2,7])
r=np.asarray(a)

C:\Users\hp\AppData\Local\Temp\ipykernel_3268\1886214294.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  r=np.asarray(a)


In [150]:
r

array([list([4, 3, 442, 8]), list([34, 345, 3]), list([645, 2, 7])],
      dtype=object)

In [172]:
from numpy import linalg
r=np.array([[4,3,2],[3,5,3],[2,2,1]])
r

array([[4, 3, 2],
       [3, 5, 3],
       [2, 2, 1]])

In [173]:
r.diagonal() #get diagonal values

array([4, 5, 1])

In [174]:
r.trace() #sum of diagonal

10

In [175]:
linalg.det(r)

-3.0000000000000004

In [176]:
linalg.inv(r)

array([[ 0.33333333, -0.33333333,  0.33333333],
       [-1.        ,  0.        ,  2.        ],
       [ 1.33333333,  0.66666667, -3.66666667]])

In [269]:
from numpy import linalg
a=np.array([[3,2],[34,2]])
b=np.array([[3,2],[34,2]])
a.diagonal()

array([3, 2])

In [270]:
a.trace()

5

In [271]:
np.dot(a,b)

array([[ 77,  10],
       [170,  72]])

In [275]:
np.inv(a)

AttributeError: module 'numpy' has no attribute 'inv'

In [181]:
marks=np.array([23,56,43,30,5,45,20,57,88])

In [184]:
np.where(marks>33,'passed','fail') #1st_arg===codition,,,2nd arg===what to do where condtion is true,,,3rd_arg===what to do where condition is not true

array(['fail', 'passed', 'passed', 'fail', 'fail', 'passed', 'fail',
       'passed', 'passed'], dtype='<U6')

In [195]:
a=np.array([[4,3,6,],[3,5,3]])
print(a)
a.mean(1)

[[4 3 6]
 [3 5 3]]


array([4.33333333, 3.66666667])

In [198]:
a=np.array([[4,3,6,],[3,5,3]])
np.cumsum(a)

array([ 4,  7, 13, 16, 21, 24])

In [204]:
a=np.array([[4,3,6,],[3,5,3]])
a=a>=4
a.sum()


3

In [205]:
a

array([[ True, False,  True],
       [False,  True, False]])

In [209]:
gender = np.array(['Male', 'Female', 'Male', 'Male', 'Male'])
arr = gender == 'Male'
arr.sum()


4

In [212]:
gender = np.array(['Male', 'Female', 'Male', 'Male', 'Male'])
arr = gender == 'Male'
arr.any()


True

In [211]:

gender = np.array(['Male', 'Female', 'Male', 'Male', 'Male'])
arr = gender == 'Male'
arr.all()

False

In [220]:
a=np.array([[4,3,6,],[3,5,3]])
np.unique(a)

array([3, 4, 5, 6])

In [239]:
a

array([[4, 3, 6],
       [3, 5, 3]])

In [228]:
np.save('1st_sav.npy',a)

In [230]:
np.load('1st_sav.npy')

array([[4, 3, 6],
       [3, 5, 3]])

In [240]:
b=np.array([[23, 23, 6],
       [13, 51, 32]])
b

array([[23, 23,  6],
       [13, 51, 32]])

In [247]:
np.savez('com.npz',ty=a,tt=b)

In [248]:
t=np.load('com.npz')

In [249]:
t['tt']

array([[23, 23,  6],
       [13, 51, 32]])

In [303]:
daud=np.random.randint(11,99,size=(3,8))
daud

array([[83, 48, 20, 32, 47, 50, 94, 47],
       [51, 30, 67, 19, 89, 60, 62, 38],
       [78, 90, 13, 33, 16, 16, 93, 23]])

In [306]:
daud.flatten()

array([83, 48, 20, 32, 47, 50, 94, 47, 51, 30, 67, 19, 89, 60, 62, 38, 78,
       90, 13, 33, 16, 16, 93, 23])

In [313]:
a = np.array([[1,2],[3,4]])
b = np.array([[7,8],[9,10]])
np.hstack((a,b))



array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

range(0, 10)

In [41]:
import numpy as np

In [44]:
plist=range(10)
for i in plist:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [1]:
print("Hello world")

Hello world


In [8]:
import numpy as np
a=np.arange(10000000)
a

array([      0,       1,       2, ..., 9999997, 9999998, 9999999])

In [ ]:
for i in range(100000):
    %time print(i*a)

[0 0 0 ... 0 0 0]
CPU times: total: 15.6 ms
Wall time: 20.9 ms
[      0       1       2 ... 9999997 9999998 9999999]
CPU times: total: 15.6 ms
Wall time: 17 ms
[       0        2        4 ... 19999994 19999996 19999998]
CPU times: total: 31.2 ms
Wall time: 18.9 ms
[       0        3        6 ... 29999991 29999994 29999997]
CPU times: total: 15.6 ms
Wall time: 17.1 ms
[       0        4        8 ... 39999988 39999992 39999996]
CPU times: total: 15.6 ms
Wall time: 17.1 ms
[       0        5       10 ... 49999985 49999990 49999995]
CPU times: total: 15.6 ms
Wall time: 16 ms
[       0        6       12 ... 59999982 59999988 59999994]
CPU times: total: 15.6 ms
Wall time: 15 ms
[       0        7       14 ... 69999979 69999986 69999993]
CPU times: total: 0 ns
Wall time: 0 ns
[       0        8       16 ... 79999976 79999984 79999992]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[       0        9       18 ... 89999973 89999982 89999991]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[       0 

[        0        80       160 ... 799999760 799999840 799999920]
CPU times: total: 15.6 ms
Wall time: 20.9 ms
[        0        81       162 ... 809999757 809999838 809999919]
CPU times: total: 31.2 ms
Wall time: 21.2 ms
[        0        82       164 ... 819999754 819999836 819999918]
CPU times: total: 15.6 ms
Wall time: 22.2 ms
[        0        83       166 ... 829999751 829999834 829999917]
CPU times: total: 15.6 ms
Wall time: 19.9 ms
[        0        84       168 ... 839999748 839999832 839999916]
CPU times: total: 31.2 ms
Wall time: 19.9 ms
[        0        85       170 ... 849999745 849999830 849999915]
CPU times: total: 15.6 ms
Wall time: 20.9 ms
[        0        86       172 ... 859999742 859999828 859999914]
CPU times: total: 15.6 ms
Wall time: 20.9 ms
[        0        87       174 ... 869999739 869999826 869999913]
CPU times: total: 31.2 ms
Wall time: 19.9 ms
[        0        88       176 ... 879999736 879999824 879999912]
CPU times: total: 15.6 ms
Wall time: 17 ms
[  

[         0        154        308 ... 1539999538 1539999692 1539999846]
CPU times: total: 31.2 ms
Wall time: 22.2 ms
[         0        155        310 ... 1549999535 1549999690 1549999845]
CPU times: total: 0 ns
Wall time: 5.49 ms
[         0        156        312 ... 1559999532 1559999688 1559999844]
CPU times: total: 15.6 ms
Wall time: 26.2 ms
[         0        157        314 ... 1569999529 1569999686 1569999843]
CPU times: total: 15.6 ms
Wall time: 15 ms
[         0        158        316 ... 1579999526 1579999684 1579999842]
CPU times: total: 0 ns
Wall time: 6.07 ms
[         0        159        318 ... 1589999523 1589999682 1589999841]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        160        320 ... 1599999520 1599999680 1599999840]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        161        322 ... 1609999517 1609999678 1609999839]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        162        324 ... 1619999514 1619999676 1619999838]


[          0         231         462 ... -1984967989 -1984967758
 -1984967527]
CPU times: total: 31.2 ms
Wall time: 22.7 ms
[          0         232         464 ... -1974967992 -1974967760
 -1974967528]
CPU times: total: 0 ns
Wall time: 4.38 ms
[          0         233         466 ... -1964967995 -1964967762
 -1964967529]
CPU times: total: 31.2 ms
Wall time: 27.8 ms
[          0         234         468 ... -1954967998 -1954967764
 -1954967530]
CPU times: total: 15.6 ms
Wall time: 20 ms
[          0         235         470 ... -1944968001 -1944967766
 -1944967531]
CPU times: total: 0 ns
Wall time: 0 ns
[          0         236         472 ... -1934968004 -1934967768
 -1934967532]
CPU times: total: 15.6 ms
Wall time: 15.7 ms
[          0         237         474 ... -1924968007 -1924967770
 -1924967533]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0         238         476 ... -1914968010 -1914967772
 -1914967534]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0       

[          0         311         622 ... -1184968229 -1184967918
 -1184967607]
CPU times: total: 15.6 ms
Wall time: 30.3 ms
[          0         312         624 ... -1174968232 -1174967920
 -1174967608]
CPU times: total: 15.6 ms
Wall time: 17.8 ms
[          0         313         626 ... -1164968235 -1164967922
 -1164967609]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0         314         628 ... -1154968238 -1154967924
 -1154967610]
CPU times: total: 0 ns
Wall time: 9.02 ms
[          0         315         630 ... -1144968241 -1144967926
 -1144967611]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0         316         632 ... -1134968244 -1134967928
 -1134967612]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0         317         634 ... -1124968247 -1124967930
 -1124967613]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0         318         636 ... -1114968250 -1114967932
 -1114967614]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0 

[         0        388        776 ... -414968460 -414968072 -414967684]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0        389        778 ... -404968463 -404968074 -404967685]
CPU times: total: 15.6 ms
Wall time: 18 ms
[         0        390        780 ... -394968466 -394968076 -394967686]
CPU times: total: 15.6 ms
Wall time: 18.8 ms
[         0        391        782 ... -384968469 -384968078 -384967687]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0        392        784 ... -374968472 -374968080 -374967688]
CPU times: total: 31.2 ms
Wall time: 18 ms
[         0        393        786 ... -364968475 -364968082 -364967689]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0        394        788 ... -354968478 -354968084 -354967690]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0        395        790 ... -344968481 -344968086 -344967691]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0        396        792 ... -334968484 -334968088 -334967692]
CPU ti

[        0       466       932 ... 365031306 365031772 365032238]
CPU times: total: 15.6 ms
Wall time: 24.6 ms
[        0       467       934 ... 375031303 375031770 375032237]
CPU times: total: 15.6 ms
Wall time: 35.1 ms
[        0       468       936 ... 385031300 385031768 385032236]
CPU times: total: 15.6 ms
Wall time: 15 ms
[        0       469       938 ... 395031297 395031766 395032235]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0       470       940 ... 405031294 405031764 405032234]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0       471       942 ... 415031291 415031762 415032233]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0       472       944 ... 425031288 425031760 425032232]
CPU times: total: 0 ns
Wall time: 9.96 ms
[        0       473       946 ... 435031285 435031758 435032231]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0       474       948 ... 445031282 445031756 445032230]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[     

[         0        540       1080 ... 1105031084 1105031624 1105032164]
CPU times: total: 0 ns
Wall time: 19.6 ms
[         0        541       1082 ... 1115031081 1115031622 1115032163]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0        542       1084 ... 1125031078 1125031620 1125032162]
CPU times: total: 15.6 ms
Wall time: 15.4 ms
[         0        543       1086 ... 1135031075 1135031618 1135032161]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        544       1088 ... 1145031072 1145031616 1145032160]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        545       1090 ... 1155031069 1155031614 1155032159]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        546       1092 ... 1165031066 1165031612 1165032158]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        547       1094 ... 1175031063 1175031610 1175032157]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        548       1096 ... 1185031060 1185031608 118503215

[         0        616       1232 ... 1865030856 1865031472 1865032088]
CPU times: total: 46.9 ms
Wall time: 36.6 ms
[         0        617       1234 ... 1875030853 1875031470 1875032087]
CPU times: total: 15.6 ms
Wall time: 27.2 ms
[         0        618       1236 ... 1885030850 1885031468 1885032086]
CPU times: total: 15.6 ms
Wall time: 12 ms
[         0        619       1238 ... 1895030847 1895031466 1895032085]
CPU times: total: 31.2 ms
Wall time: 31.2 ms
[         0        620       1240 ... 1905030844 1905031464 1905032084]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        621       1242 ... 1915030841 1915031462 1915032083]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        622       1244 ... 1925030838 1925031460 1925032082]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        623       1246 ... 1935030835 1935031458 1935032081]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        624       1248 ... 1945030832 1945031456 194503

[          0         689        1378 ... -1699936659 -1699935970
 -1699935281]
CPU times: total: 15.6 ms
Wall time: 18 ms
[          0         690        1380 ... -1689936662 -1689935972
 -1689935282]
CPU times: total: 15.6 ms
Wall time: 14.6 ms
[          0         691        1382 ... -1679936665 -1679935974
 -1679935283]
CPU times: total: 15.6 ms
Wall time: 20.4 ms
[          0         692        1384 ... -1669936668 -1669935976
 -1669935284]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0         693        1386 ... -1659936671 -1659935978
 -1659935285]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0         694        1388 ... -1649936674 -1649935980
 -1649935286]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0         695        1390 ... -1639936677 -1639935982
 -1639935287]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0         696        1392 ... -1629936680 -1629935984
 -1629935288]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0        

[         0        763       1526 ... -959936881 -959936118 -959935355]
CPU times: total: 15.6 ms
Wall time: 28.2 ms
[         0        764       1528 ... -949936884 -949936120 -949935356]
CPU times: total: 15.6 ms
Wall time: 18 ms
[         0        765       1530 ... -939936887 -939936122 -939935357]
CPU times: total: 0 ns
Wall time: 17.4 ms
[         0        766       1532 ... -929936890 -929936124 -929935358]
CPU times: total: 15.6 ms
Wall time: 15.5 ms
[         0        767       1534 ... -919936893 -919936126 -919935359]
CPU times: total: 15.6 ms
Wall time: 18.3 ms
[         0        768       1536 ... -909936896 -909936128 -909935360]
CPU times: total: 15.6 ms
Wall time: 14.1 ms
[         0        769       1538 ... -899936899 -899936130 -899935361]
CPU times: total: 15.6 ms
Wall time: 19.4 ms
[         0        770       1540 ... -889936902 -889936132 -889935362]
CPU times: total: 15.6 ms
Wall time: 12.8 ms
[         0        771       1542 ... -879936905 -879936134 -87993536

[         0        835       1670 ... -239937097 -239936262 -239935427]
CPU times: total: 0 ns
Wall time: 21.9 ms
[         0        836       1672 ... -229937100 -229936264 -229935428]
CPU times: total: 15.6 ms
Wall time: 18.9 ms
[         0        837       1674 ... -219937103 -219936266 -219935429]
CPU times: total: 15.6 ms
Wall time: 18 ms
[         0        838       1676 ... -209937106 -209936268 -209935430]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0        839       1678 ... -199937109 -199936270 -199935431]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0        840       1680 ... -189937112 -189936272 -189935432]
CPU times: total: 31.2 ms
Wall time: 24.9 ms
[         0        841       1682 ... -179937115 -179936274 -179935433]
CPU times: total: 31.2 ms
Wall time: 24.9 ms
[         0        842       1684 ... -169937118 -169936276 -169935434]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0        843       1686 ... -159937121 -159936278 -159935435]
CPU

[        0       910      1820 ... 510062678 510063588 510064498]
CPU times: total: 0 ns
Wall time: 3.09 ms
[        0       911      1822 ... 520062675 520063586 520064497]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0       912      1824 ... 530062672 530063584 530064496]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0       913      1826 ... 540062669 540063582 540064495]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0       914      1828 ... 550062666 550063580 550064494]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0       915      1830 ... 560062663 560063578 560064493]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0       916      1832 ... 570062660 570063576 570064492]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0       917      1834 ... 580062657 580063574 580064491]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0       918      1836 ... 590062654 590063572 590064490]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[   

[         0        985       1970 ... 1260062453 1260063438 1260064423]
CPU times: total: 31.2 ms
Wall time: 28.5 ms
[         0        986       1972 ... 1270062450 1270063436 1270064422]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0        987       1974 ... 1280062447 1280063434 1280064421]
CPU times: total: 15.6 ms
Wall time: 15 ms
[         0        988       1976 ... 1290062444 1290063432 1290064420]
CPU times: total: 15.6 ms
Wall time: 15 ms
[         0        989       1978 ... 1300062441 1300063430 1300064419]
CPU times: total: 0 ns
Wall time: 1.53 ms
[         0        990       1980 ... 1310062438 1310063428 1310064418]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0        991       1982 ... 1320062435 1320063426 1320064417]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0        992       1984 ... 1330062432 1330063424 1330064416]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0        993       1986 ... 1340062429 1340063422 1340064415]
CPU t

[         0       1063       2126 ... 2040062219 2040063282 2040064345]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1064       2128 ... 2050062216 2050063280 2050064344]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1065       2130 ... 2060062213 2060063278 2060064343]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1066       2132 ... 2070062210 2070063276 2070064342]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1067       2134 ... 2080062207 2080063274 2080064341]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1068       2136 ... 2090062204 2090063272 2090064340]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1069       2138 ... 2100062201 2100063270 2100064339]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1070       2140 ... 2110062198 2110063268 2110064338]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1071       2142 ... 2120062195 2120063266 2120

[          0        1138        2276 ... -1504905302 -1504904164
 -1504903026]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        1139        2278 ... -1494905305 -1494904166
 -1494903027]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        1140        2280 ... -1484905308 -1484904168
 -1484903028]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        1141        2282 ... -1474905311 -1474904170
 -1474903029]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        1142        2284 ... -1464905314 -1464904172
 -1464903030]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        1143        2286 ... -1454905317 -1454904174
 -1454903031]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        1144        2288 ... -1444905320 -1444904176
 -1444903032]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        1145        2290 ... -1434905323 -1434904178
 -1434903033]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[       

[         0       1217       2434 ... -714905539 -714904322 -714903105]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1218       2436 ... -704905542 -704904324 -704903106]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1219       2438 ... -694905545 -694904326 -694903107]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1220       2440 ... -684905548 -684904328 -684903108]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1221       2442 ... -674905551 -674904330 -674903109]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1222       2444 ... -664905554 -664904332 -664903110]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1223       2446 ... -654905557 -654904334 -654903111]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1224       2448 ... -644905560 -644904336 -644903112]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1225       2450 ... -634905563 -634904338 -634

[       0     1297     2594 ... 85094221 85095518 85096815]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[       0     1298     2596 ... 95094218 95095516 95096814]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1299      2598 ... 105094215 105095514 105096813]
CPU times: total: 0 ns
Wall time: 0 ns
[        0      1300      2600 ... 115094212 115095512 115096812]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1301      2602 ... 125094209 125095510 125096811]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1302      2604 ... 135094206 135095508 135096810]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1303      2606 ... 145094203 145095506 145096809]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1304      2608 ... 155094200 155095504 155096808]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1305      2610 ... 165094197 165095502 165096807]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      130

[        0      1376      2752 ... 875093984 875095360 875096736]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1377      2754 ... 885093981 885095358 885096735]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1378      2756 ... 895093978 895095356 895096734]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1379      2758 ... 905093975 905095354 905096733]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1380      2760 ... 915093972 915095352 915096732]
CPU times: total: 31.2 ms
Wall time: 31.3 ms
[        0      1381      2762 ... 925093969 925095350 925096731]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1382      2764 ... 935093966 935095348 935096730]
CPU times: total: 31.2 ms
Wall time: 31.2 ms
[        0      1383      2766 ... 945093963 945095346 945096729]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      1384      2768 ... 955093960 955095344 955096728]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[

[         0       1455       2910 ... 1665093747 1665095202 1665096657]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1456       2912 ... 1675093744 1675095200 1675096656]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1457       2914 ... 1685093741 1685095198 1685096655]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1458       2916 ... 1695093738 1695095196 1695096654]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1459       2918 ... 1705093735 1705095194 1705096653]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1460       2920 ... 1715093732 1715095192 1715096652]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1461       2922 ... 1725093729 1725095190 1725096651]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1462       2924 ... 1735093726 1735095188 1735096650]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1463       2926 ... 1745093723 1745095186 1745

[          0        1532        3064 ... -1859873780 -1859872248
 -1859870716]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        1533        3066 ... -1849873783 -1849872250
 -1849870717]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        1534        3068 ... -1839873786 -1839872252
 -1839870718]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0        1535        3070 ... -1829873789 -1829872254
 -1829870719]
CPU times: total: 15.6 ms
Wall time: 18.9 ms
[          0        1536        3072 ... -1819873792 -1819872256
 -1819870720]
CPU times: total: 15.6 ms
Wall time: 14.9 ms
[          0        1537        3074 ... -1809873795 -1809872258
 -1809870721]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        1538        3076 ... -1799873798 -1799872260
 -1799870722]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        1539        3078 ... -1789873801 -1789872262
 -1789870723]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0  

[          0        1606        3212 ... -1119874002 -1119872396
 -1119870790]
CPU times: total: 31.2 ms
Wall time: 16 ms
[          0        1607        3214 ... -1109874005 -1109872398
 -1109870791]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        1608        3216 ... -1099874008 -1099872400
 -1099870792]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0        1609        3218 ... -1089874011 -1089872402
 -1089870793]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        1610        3220 ... -1079874014 -1079872404
 -1079870794]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0        1611        3222 ... -1069874017 -1069872406
 -1069870795]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0        1612        3224 ... -1059874020 -1059872408
 -1059870796]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0        1613        3226 ... -1049874023 -1049872410
 -1049870797]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0        1614

[         0       1682       3364 ... -359874230 -359872548 -359870866]
CPU times: total: 15.6 ms
Wall time: 23.9 ms
[         0       1683       3366 ... -349874233 -349872550 -349870867]
CPU times: total: 31.2 ms
Wall time: 23.9 ms
[         0       1684       3368 ... -339874236 -339872552 -339870868]
CPU times: total: 15.6 ms
Wall time: 23.9 ms
[         0       1685       3370 ... -329874239 -329872554 -329870869]
CPU times: total: 31.2 ms
Wall time: 23.9 ms
[         0       1686       3372 ... -319874242 -319872556 -319870870]
CPU times: total: 15.6 ms
Wall time: 22.9 ms
[         0       1687       3374 ... -309874245 -309872558 -309870871]
CPU times: total: 31.2 ms
Wall time: 17 ms
[         0       1688       3376 ... -299874248 -299872560 -299870872]
CPU times: total: 15.6 ms
Wall time: 16.9 ms
[         0       1689       3378 ... -289874251 -289872562 -289870873]
CPU times: total: 15.6 ms
Wall time: 16.9 ms
[         0       1690       3380 ... -279874254 -279872564 -27987

[        0      1756      3512 ... 380125548 380127304 380129060]
CPU times: total: 31.2 ms
Wall time: 17 ms
[        0      1757      3514 ... 390125545 390127302 390129059]
CPU times: total: 15.6 ms
Wall time: 17 ms
[        0      1758      3516 ... 400125542 400127300 400129058]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      1759      3518 ... 410125539 410127298 410129057]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      1760      3520 ... 420125536 420127296 420129056]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      1761      3522 ... 430125533 430127294 430129055]
CPU times: total: 15.6 ms
Wall time: 17 ms
[        0      1762      3524 ... 440125530 440127292 440129054]
CPU times: total: 15.6 ms
Wall time: 17 ms
[        0      1763      3526 ... 450125527 450127290 450129053]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      1764      3528 ... 460125524 460127288 460129052]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      176

[         0       1832       3664 ... 1140125320 1140127152 1140128984]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1833       3666 ... 1150125317 1150127150 1150128983]
CPU times: total: 31.2 ms
Wall time: 31.2 ms
[         0       1834       3668 ... 1160125314 1160127148 1160128982]
CPU times: total: 15.6 ms
Wall time: 20.2 ms
[         0       1835       3670 ... 1170125311 1170127146 1170128981]
CPU times: total: 15.6 ms
Wall time: 20.9 ms
[         0       1836       3672 ... 1180125308 1180127144 1180128980]
CPU times: total: 31.2 ms
Wall time: 19.9 ms
[         0       1837       3674 ... 1190125305 1190127142 1190128979]
CPU times: total: 15.6 ms
Wall time: 21.7 ms
[         0       1838       3676 ... 1200125302 1200127140 1200128978]
CPU times: total: 0 ns
Wall time: 7.66 ms
[         0       1839       3678 ... 1210125299 1210127138 1210128977]
CPU times: total: 31.2 ms
Wall time: 33.4 ms
[         0       1840       3680 ... 1220125296 1220127136 1220128

[         0       1903       3806 ... 1850125107 1850127010 1850128913]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1904       3808 ... 1860125104 1860127008 1860128912]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1905       3810 ... 1870125101 1870127006 1870128911]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1906       3812 ... 1880125098 1880127004 1880128910]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1907       3814 ... 1890125095 1890127002 1890128909]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1908       3816 ... 1900125092 1900127000 1900128908]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1909       3818 ... 1910125089 1910126998 1910128907]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1910       3820 ... 1920125086 1920126996 1920128906]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       1911       3822 ... 1930125083 1930126994 1930

[          0        1976        3952 ... -1714842408 -1714840432
 -1714838456]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        1977        3954 ... -1704842411 -1704840434
 -1704838457]
CPU times: total: 15.6 ms
Wall time: 15.8 ms
[          0        1978        3956 ... -1694842414 -1694840436
 -1694838458]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        1979        3958 ... -1684842417 -1684840438
 -1684838459]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        1980        3960 ... -1674842420 -1674840440
 -1674838460]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        1981        3962 ... -1664842423 -1664840442
 -1664838461]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        1982        3964 ... -1654842426 -1654840444
 -1654838462]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0        1983        3966 ... -1644842429 -1644840446
 -1644838463]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0        

[         0       2049       4098 ... -984842627 -984840578 -984838529]
CPU times: total: 15.6 ms
Wall time: 19.1 ms
[         0       2050       4100 ... -974842630 -974840580 -974838530]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0       2051       4102 ... -964842633 -964840582 -964838531]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       2052       4104 ... -954842636 -954840584 -954838532]
CPU times: total: 15.6 ms
Wall time: 8.02 ms
[         0       2053       4106 ... -944842639 -944840586 -944838533]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       2054       4108 ... -934842642 -934840588 -934838534]
CPU times: total: 15.6 ms
Wall time: 24.3 ms
[         0       2055       4110 ... -924842645 -924840590 -924838535]
CPU times: total: 31.2 ms
Wall time: 21.1 ms
[         0       2056       4112 ... -914842648 -914840592 -914838536]
CPU times: total: 0 ns
Wall time: 9.66 ms
[         0       2057       4114 ... -904842651 -904840594 -904838537]

[         0       2123       4246 ... -244842849 -244840726 -244838603]
CPU times: total: 15.6 ms
Wall time: 15.9 ms
[         0       2124       4248 ... -234842852 -234840728 -234838604]
CPU times: total: 15.6 ms
Wall time: 16.3 ms
[         0       2125       4250 ... -224842855 -224840730 -224838605]
CPU times: total: 15.6 ms
Wall time: 17.3 ms
[         0       2126       4252 ... -214842858 -214840732 -214838606]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       2127       4254 ... -204842861 -204840734 -204838607]
CPU times: total: 15.6 ms
Wall time: 7.02 ms
[         0       2128       4256 ... -194842864 -194840736 -194838608]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       2129       4258 ... -184842867 -184840738 -184838609]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       2130       4260 ... -174842870 -174840740 -174838610]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       2131       4262 ... -164842873 -164840742 -16483

[        0      2198      4396 ... 505156926 505159124 505161322]
CPU times: total: 46.9 ms
Wall time: 35.1 ms
[        0      2199      4398 ... 515156923 515159122 515161321]
CPU times: total: 15.6 ms
Wall time: 18.3 ms
[        0      2200      4400 ... 525156920 525159120 525161320]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      2201      4402 ... 535156917 535159118 535161319]
CPU times: total: 0 ns
Wall time: 2.39 ms
[        0      2202      4404 ... 545156914 545159116 545161318]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      2203      4406 ... 555156911 555159114 555161317]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      2204      4408 ... 565156908 565159112 565161316]
CPU times: total: 31.2 ms
Wall time: 29.6 ms
[        0      2205      4410 ... 575156905 575159110 575161315]
CPU times: total: 15.6 ms
Wall time: 17.2 ms
[        0      2206      4412 ... 585156902 585159108 585161314]
CPU times: total: 15.6 ms
Wall time: 17.1 ms
[     

[         0       2278       4556 ... 1305156686 1305158964 1305161242]
CPU times: total: 31.2 ms
Wall time: 26.1 ms
[         0       2279       4558 ... 1315156683 1315158962 1315161241]
CPU times: total: 0 ns
Wall time: 16.3 ms
[         0       2280       4560 ... 1325156680 1325158960 1325161240]
CPU times: total: 15.6 ms
Wall time: 18 ms
[         0       2281       4562 ... 1335156677 1335158958 1335161239]
CPU times: total: 15.6 ms
Wall time: 14 ms
[         0       2282       4564 ... 1345156674 1345158956 1345161238]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       2283       4566 ... 1355156671 1355158954 1355161237]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       2284       4568 ... 1365156668 1365158952 1365161236]
CPU times: total: 15.6 ms
Wall time: 19 ms
[         0       2285       4570 ... 1375156665 1375158950 1375161235]
CPU times: total: 0 ns
Wall time: 15.6 ms
[         0       2286       4572 ... 1385156662 1385158948 1385161234]
CPU 

[         0       2351       4702 ... 2035156467 2035158818 2035161169]
CPU times: total: 15.6 ms
Wall time: 18.5 ms
[         0       2352       4704 ... 2045156464 2045158816 2045161168]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       2353       4706 ... 2055156461 2055158814 2055161167]
CPU times: total: 15.6 ms
Wall time: 15 ms
[         0       2354       4708 ... 2065156458 2065158812 2065161166]
CPU times: total: 15.6 ms
Wall time: 18.1 ms
[         0       2355       4710 ... 2075156455 2075158810 2075161165]
CPU times: total: 31.2 ms
Wall time: 16.9 ms
[         0       2356       4712 ... 2085156452 2085158808 2085161164]
CPU times: total: 15.6 ms
Wall time: 16.3 ms
[         0       2357       4714 ... 2095156449 2095158806 2095161163]
CPU times: total: 15.6 ms
Wall time: 16.6 ms
[         0       2358       4716 ... 2105156446 2105158804 2105161162]
CPU times: total: 0 ns
Wall time: 17.6 ms
[         0       2359       4718 ... 2115156443 2115158802 2115161161]

[          0        2422        4844 ... -1549811042 -1549808620
 -1549806198]
CPU times: total: 15.6 ms
Wall time: 22.9 ms
[          0        2423        4846 ... -1539811045 -1539808622
 -1539806199]
CPU times: total: 31.2 ms
Wall time: 23.9 ms
[          0        2424        4848 ... -1529811048 -1529808624
 -1529806200]
CPU times: total: 31.2 ms
Wall time: 25.9 ms
[          0        2425        4850 ... -1519811051 -1519808626
 -1519806201]
CPU times: total: 15.6 ms
Wall time: 22.9 ms
[          0        2426        4852 ... -1509811054 -1509808628
 -1509806202]
CPU times: total: 31.2 ms
Wall time: 23.9 ms
[          0        2427        4854 ... -1499811057 -1499808630
 -1499806203]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        2428        4856 ... -1489811060 -1489808632
 -1489806204]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        2429        4858 ... -1479811063 -1479808634
 -1479806205]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0  

[         0       2493       4986 ... -839811255 -839808762 -839806269]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0       2494       4988 ... -829811258 -829808764 -829806270]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0       2495       4990 ... -819811261 -819808766 -819806271]
CPU times: total: 0 ns
Wall time: 16 ms
[         0       2496       4992 ... -809811264 -809808768 -809806272]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       2497       4994 ... -799811267 -799808770 -799806273]
CPU times: total: 15.6 ms
Wall time: 3.47 ms
[         0       2498       4996 ... -789811270 -789808772 -789806274]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       2499       4998 ... -779811273 -779808774 -779806275]
CPU times: total: 31.2 ms
Wall time: 31.2 ms
[         0       2500       5000 ... -769811276 -769808776 -769806276]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       2501       5002 ... -759811279 -759808778 -759806277]
CPU

[        0      2567      5134 ... -99811477 -99808910 -99806343]
CPU times: total: 15.6 ms
Wall time: 16.5 ms
[        0      2568      5136 ... -89811480 -89808912 -89806344]
CPU times: total: 15.6 ms
Wall time: 15.7 ms
[        0      2569      5138 ... -79811483 -79808914 -79806345]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      2570      5140 ... -69811486 -69808916 -69806346]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      2571      5142 ... -59811489 -59808918 -59806347]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      2572      5144 ... -49811492 -49808920 -49806348]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      2573      5146 ... -39811495 -39808922 -39806349]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      2574      5148 ... -29811498 -29808924 -29806350]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      2575      5150 ... -19811501 -19808926 -19806351]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[

[        0      2642      5284 ... 650188298 650190940 650193582]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      2643      5286 ... 660188295 660190938 660193581]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      2644      5288 ... 670188292 670190936 670193580]
CPU times: total: 15.6 ms
Wall time: 20.1 ms
[        0      2645      5290 ... 680188289 680190934 680193579]
CPU times: total: 15.6 ms
Wall time: 10.5 ms
[        0      2646      5292 ... 690188286 690190932 690193578]
CPU times: total: 0 ns
Wall time: 24.8 ms
[        0      2647      5294 ... 700188283 700190930 700193577]
CPU times: total: 31.2 ms
Wall time: 18 ms
[        0      2648      5296 ... 710188280 710190928 710193576]
CPU times: total: 0 ns
Wall time: 7.41 ms
[        0      2649      5298 ... 720188277 720190926 720193575]
CPU times: total: 15.6 ms
Wall time: 33.1 ms
[        0      2650      5300 ... 730188274 730190924 730193574]
CPU times: total: 31.2 ms
Wall time: 32.6 ms
[        

[         0       2723       5446 ... 1460188055 1460190778 1460193501]
CPU times: total: 31.2 ms
Wall time: 16 ms
[         0       2724       5448 ... 1470188052 1470190776 1470193500]
CPU times: total: 0 ns
Wall time: 17 ms
[         0       2725       5450 ... 1480188049 1480190774 1480193499]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       2726       5452 ... 1490188046 1490190772 1490193498]
CPU times: total: 15.6 ms
Wall time: 17.4 ms
[         0       2727       5454 ... 1500188043 1500190770 1500193497]
CPU times: total: 15.6 ms
Wall time: 16.4 ms
[         0       2728       5456 ... 1510188040 1510190768 1510193496]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0       2729       5458 ... 1520188037 1520190766 1520193495]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0       2730       5460 ... 1530188034 1530190764 1530193494]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0       2731       5462 ... 1540188031 1540190762 1540193493]
CPU tim

[          0        2799        5598 ... -2074779469 -2074776670
 -2074773871]
CPU times: total: 31.2 ms
Wall time: 19.7 ms
[          0        2800        5600 ... -2064779472 -2064776672
 -2064773872]
CPU times: total: 15.6 ms
Wall time: 16.4 ms
[          0        2801        5602 ... -2054779475 -2054776674
 -2054773873]
CPU times: total: 0 ns
Wall time: 17.7 ms
[          0        2802        5604 ... -2044779478 -2044776676
 -2044773874]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        2803        5606 ... -2034779481 -2034776678
 -2034773875]
CPU times: total: 15.6 ms
Wall time: 14 ms
[          0        2804        5608 ... -2024779484 -2024776680
 -2024773876]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        2805        5610 ... -2014779487 -2014776682
 -2014773877]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        2806        5612 ... -2004779490 -2004776684
 -2004773878]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0   

[          0        2876        5752 ... -1304779700 -1304776824
 -1304773948]
CPU times: total: 15.6 ms
Wall time: 26.3 ms
[          0        2877        5754 ... -1294779703 -1294776826
 -1294773949]
CPU times: total: 31.2 ms
Wall time: 24.5 ms
[          0        2878        5756 ... -1284779706 -1284776828
 -1284773950]
CPU times: total: 15.6 ms
Wall time: 22.9 ms
[          0        2879        5758 ... -1274779709 -1274776830
 -1274773951]
CPU times: total: 15.6 ms
Wall time: 7.55 ms
[          0        2880        5760 ... -1264779712 -1264776832
 -1264773952]
CPU times: total: 31.2 ms
Wall time: 35.8 ms
[          0        2881        5762 ... -1254779715 -1254776834
 -1254773953]
CPU times: total: 15.6 ms
Wall time: 14.1 ms
[          0        2882        5764 ... -1244779718 -1244776836
 -1244773954]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        2883        5766 ... -1234779721 -1234776838
 -1234773955]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[       

[         0       2953       5906 ... -534779931 -534776978 -534774025]
CPU times: total: 31.2 ms
Wall time: 25.6 ms
[         0       2954       5908 ... -524779934 -524776980 -524774026]
CPU times: total: 0 ns
Wall time: 8.61 ms
[         0       2955       5910 ... -514779937 -514776982 -514774027]
CPU times: total: 15.6 ms
Wall time: 21 ms
[         0       2956       5912 ... -504779940 -504776984 -504774028]
CPU times: total: 31.2 ms
Wall time: 20.4 ms
[         0       2957       5914 ... -494779943 -494776986 -494774029]
CPU times: total: 15.6 ms
Wall time: 15 ms
[         0       2958       5916 ... -484779946 -484776988 -484774030]
CPU times: total: 0 ns
Wall time: 10 ms
[         0       2959       5918 ... -474779949 -474776990 -474774031]
CPU times: total: 31.2 ms
Wall time: 22.6 ms
[         0       2960       5920 ... -464779952 -464776992 -464774032]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       2961       5922 ... -454779955 -454776994 -454774033]
CPU 

[        0      3033      6066 ... 265219829 265222862 265225895]
CPU times: total: 15.6 ms
Wall time: 17.9 ms
[        0      3034      6068 ... 275219826 275222860 275225894]
CPU times: total: 31.2 ms
Wall time: 17.9 ms
[        0      3035      6070 ... 285219823 285222858 285225893]
CPU times: total: 15.6 ms
Wall time: 17 ms
[        0      3036      6072 ... 295219820 295222856 295225892]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      3037      6074 ... 305219817 305222854 305225891]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      3038      6076 ... 315219814 315222852 315225890]
CPU times: total: 15.6 ms
Wall time: 17 ms
[        0      3039      6078 ... 325219811 325222850 325225889]
CPU times: total: 15.6 ms
Wall time: 17 ms
[        0      3040      6080 ... 335219808 335222848 335225888]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      3041      6082 ... 345219805 345222846 345225887]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0     

[         0       3116       6232 ... 1095219580 1095222696 1095225812]
CPU times: total: 31.2 ms
Wall time: 29.1 ms
[         0       3117       6234 ... 1105219577 1105222694 1105225811]
CPU times: total: 15.6 ms
Wall time: 17.7 ms
[         0       3118       6236 ... 1115219574 1115222692 1115225810]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       3119       6238 ... 1125219571 1125222690 1125225809]
CPU times: total: 15.6 ms
Wall time: 10.1 ms
[         0       3120       6240 ... 1135219568 1135222688 1135225808]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       3121       6242 ... 1145219565 1145222686 1145225807]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       3122       6244 ... 1155219562 1155222684 1155225806]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       3123       6246 ... 1165219559 1165222682 1165225805]
CPU times: total: 15.6 ms
Wall time: 42.7 ms
[         0       3124       6248 ... 1175219556 1175222680 117522

[         0       3194       6388 ... 1875219346 1875222540 1875225734]
CPU times: total: 15.6 ms
Wall time: 30.9 ms
[         0       3195       6390 ... 1885219343 1885222538 1885225733]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       3196       6392 ... 1895219340 1895222536 1895225732]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       3197       6394 ... 1905219337 1905222534 1905225731]
CPU times: total: 15.6 ms
Wall time: 6.07 ms
[         0       3198       6396 ... 1915219334 1915222532 1915225730]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       3199       6398 ... 1925219331 1925222530 1925225729]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       3200       6400 ... 1935219328 1935222528 1935225728]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       3201       6402 ... 1945219325 1945222526 1945225727]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       3202       6404 ... 1955219322 1955222524 19552257

[          0        3273        6546 ... -1629748187 -1629744914
 -1629741641]
CPU times: total: 15.6 ms
Wall time: 29.8 ms
[          0        3274        6548 ... -1619748190 -1619744916
 -1619741642]
CPU times: total: 31.2 ms
Wall time: 16.9 ms
[          0        3275        6550 ... -1609748193 -1609744918
 -1609741643]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        3276        6552 ... -1599748196 -1599744920
 -1599741644]
CPU times: total: 0 ns
Wall time: 7.38 ms
[          0        3277        6554 ... -1589748199 -1589744922
 -1589741645]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        3278        6556 ... -1579748202 -1579744924
 -1579741646]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        3279        6558 ... -1569748205 -1569744926
 -1569741647]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        3280        6560 ... -1559748208 -1559744928
 -1559741648]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0 

[         0       3346       6692 ... -899748406 -899745060 -899741714]
CPU times: total: 15.6 ms
Wall time: 19.9 ms
[         0       3347       6694 ... -889748409 -889745062 -889741715]
CPU times: total: 31.2 ms
Wall time: 20.9 ms
[         0       3348       6696 ... -879748412 -879745064 -879741716]
CPU times: total: 15.6 ms
Wall time: 25.9 ms
[         0       3349       6698 ... -869748415 -869745066 -869741717]
CPU times: total: 31.2 ms
Wall time: 19.9 ms
[         0       3350       6700 ... -859748418 -859745068 -859741718]
CPU times: total: 15.6 ms
Wall time: 28 ms
[         0       3351       6702 ... -849748421 -849745070 -849741719]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       3352       6704 ... -839748424 -839745072 -839741720]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       3353       6706 ... -829748427 -829745074 -829741721]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       3354       6708 ... -819748430 -819745076 -81974

[         0       3424       6848 ... -119748640 -119745216 -119741792]
CPU times: total: 15.6 ms
Wall time: 20.5 ms
[         0       3425       6850 ... -109748643 -109745218 -109741793]
CPU times: total: 15.6 ms
Wall time: 13.2 ms
[        0      3426      6852 ... -99748646 -99745220 -99741794]
CPU times: total: 46.9 ms
Wall time: 38.6 ms
[        0      3427      6854 ... -89748649 -89745222 -89741795]
CPU times: total: 15.6 ms
Wall time: 21.9 ms
[        0      3428      6856 ... -79748652 -79745224 -79741796]
CPU times: total: 15.6 ms
Wall time: 20.2 ms
[        0      3429      6858 ... -69748655 -69745226 -69741797]
CPU times: total: 31.2 ms
Wall time: 28.2 ms
[        0      3430      6860 ... -59748658 -59745228 -59741798]
CPU times: total: 15.6 ms
Wall time: 18 ms
[        0      3431      6862 ... -49748661 -49745230 -49741799]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      3432      6864 ... -39748664 -39745232 -39741800]
CPU times: total: 31.2 ms
Wall time: 1

[        0      3505      7010 ... 690251117 690254622 690258127]
CPU times: total: 31.2 ms
Wall time: 23.1 ms
[        0      3506      7012 ... 700251114 700254620 700258126]
CPU times: total: 15.6 ms
Wall time: 16.7 ms
[        0      3507      7014 ... 710251111 710254618 710258125]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      3508      7016 ... 720251108 720254616 720258124]
CPU times: total: 0 ns
Wall time: 7.42 ms
[        0      3509      7018 ... 730251105 730254614 730258123]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      3510      7020 ... 740251102 740254612 740258122]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      3511      7022 ... 750251099 750254610 750258121]
CPU times: total: 31.2 ms
Wall time: 28.6 ms
[        0      3512      7024 ... 760251096 760254608 760258120]
CPU times: total: 15.6 ms
Wall time: 16 ms
[        0      3513      7026 ... 770251093 770254606 770258119]
CPU times: total: 15.6 ms
Wall time: 17 ms
[        0

[         0       3581       7162 ... 1450250889 1450254470 1450258051]
CPU times: total: 15.6 ms
Wall time: 19.3 ms
[         0       3582       7164 ... 1460250886 1460254468 1460258050]
CPU times: total: 0 ns
Wall time: 2.21 ms
[         0       3583       7166 ... 1470250883 1470254466 1470258049]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       3584       7168 ... 1480250880 1480254464 1480258048]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       3585       7170 ... 1490250877 1490254462 1490258047]
CPU times: total: 15.6 ms
Wall time: 16.7 ms
[         0       3586       7172 ... 1500250874 1500254460 1500258046]
CPU times: total: 31.2 ms
Wall time: 31.2 ms
[         0       3587       7174 ... 1510250871 1510254458 1510258045]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       3588       7176 ... 1520250868 1520254456 1520258044]
CPU times: total: 31.2 ms
Wall time: 31.2 ms
[         0       3589       7178 ... 1530250865 1530254454 1530258043]

[          0        3658        7316 ... -2074716638 -2074712980
 -2074709322]
CPU times: total: 15.6 ms
Wall time: 25 ms
[          0        3659        7318 ... -2064716641 -2064712982
 -2064709323]
CPU times: total: 31.2 ms
Wall time: 16.4 ms
[          0        3660        7320 ... -2054716644 -2054712984
 -2054709324]
CPU times: total: 15.6 ms
Wall time: 17 ms
[          0        3661        7322 ... -2044716647 -2044712986
 -2044709325]
CPU times: total: 15.6 ms
Wall time: 15 ms
[          0        3662        7324 ... -2034716650 -2034712988
 -2034709326]
CPU times: total: 0 ns
Wall time: 2.08 ms
[          0        3663        7326 ... -2024716653 -2024712990
 -2024709327]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        3664        7328 ... -2014716656 -2014712992
 -2014709328]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        3665        7330 ... -2004716659 -2004712994
 -2004709329]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0     

[          0        3738        7476 ... -1274716878 -1274713140
 -1274709402]
CPU times: total: 15.6 ms
Wall time: 30.2 ms
[          0        3739        7478 ... -1264716881 -1264713142
 -1264709403]
CPU times: total: 0 ns
Wall time: 19.6 ms
[          0        3740        7480 ... -1254716884 -1254713144
 -1254709404]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        3741        7482 ... -1244716887 -1244713146
 -1244709405]
CPU times: total: 15.6 ms
Wall time: 6.57 ms
[          0        3742        7484 ... -1234716890 -1234713148
 -1234709406]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        3743        7486 ... -1224716893 -1224713150
 -1224709407]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        3744        7488 ... -1214716896 -1214713152
 -1214709408]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        3745        7490 ... -1204716899 -1204713154
 -1204709409]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0 

[         0       3816       7632 ... -494717112 -494713296 -494709480]
CPU times: total: 15.6 ms
Wall time: 18 ms
[         0       3817       7634 ... -484717115 -484713298 -484709481]
CPU times: total: 15.6 ms
Wall time: 20 ms
[         0       3818       7636 ... -474717118 -474713300 -474709482]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0       3819       7638 ... -464717121 -464713302 -464709483]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       3820       7640 ... -454717124 -454713304 -454709484]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0       3821       7642 ... -444717127 -444713306 -444709485]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       3822       7644 ... -434717130 -434713308 -434709486]
CPU times: total: 15.6 ms
Wall time: 24.9 ms
[         0       3823       7646 ... -424717133 -424713310 -424709487]
CPU times: total: 15.6 ms
Wall time: 17.1 ms
[         0       3824       7648 ... -414717136 -414713312 -414709488]
CPU 

[        0      3898      7796 ... 325282642 325286540 325290438]
CPU times: total: 15.6 ms
Wall time: 22.2 ms
[        0      3899      7798 ... 335282639 335286538 335290437]
CPU times: total: 15.6 ms
Wall time: 11.5 ms
[        0      3900      7800 ... 345282636 345286536 345290436]
CPU times: total: 15.6 ms
Wall time: 22.7 ms
[        0      3901      7802 ... 355282633 355286534 355290435]
CPU times: total: 31.2 ms
Wall time: 15.9 ms
[        0      3902      7804 ... 365282630 365286532 365290434]
CPU times: total: 0 ns
Wall time: 11 ms
[        0      3903      7806 ... 375282627 375286530 375290433]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      3904      7808 ... 385282624 385286528 385290432]
CPU times: total: 15.6 ms
Wall time: 15.7 ms
[        0      3905      7810 ... 395282621 395286526 395290431]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      3906      7812 ... 405282618 405286524 405290430]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[     

[         0       3975       7950 ... 1095282411 1095286386 1095290361]
CPU times: total: 15.6 ms
Wall time: 17.9 ms
[         0       3976       7952 ... 1105282408 1105286384 1105290360]
CPU times: total: 15.6 ms
Wall time: 18.7 ms
[         0       3977       7954 ... 1115282405 1115286382 1115290359]
CPU times: total: 15.6 ms
Wall time: 17.8 ms
[         0       3978       7956 ... 1125282402 1125286380 1125290358]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0       3979       7958 ... 1135282399 1135286378 1135290357]
CPU times: total: 15.6 ms
Wall time: 18 ms
[         0       3980       7960 ... 1145282396 1145286376 1145290356]
CPU times: total: 15.6 ms
Wall time: 16.5 ms
[         0       3981       7962 ... 1155282393 1155286374 1155290355]
CPU times: total: 31.2 ms
Wall time: 17 ms
[         0       3982       7964 ... 1165282390 1165286372 1165290354]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       3983       7966 ... 1175282387 1175286370 1175290353]


[         0       4049       8098 ... 1835282189 1835286238 1835290287]
CPU times: total: 15.6 ms
Wall time: 29.1 ms
[         0       4050       8100 ... 1845282186 1845286236 1845290286]
CPU times: total: 31.2 ms
Wall time: 24.9 ms
[         0       4051       8102 ... 1855282183 1855286234 1855290285]
CPU times: total: 15.6 ms
Wall time: 20.1 ms
[         0       4052       8104 ... 1865282180 1865286232 1865290284]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       4053       8106 ... 1875282177 1875286230 1875290283]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       4054       8108 ... 1885282174 1885286228 1885290282]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       4055       8110 ... 1895282171 1895286226 1895290281]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       4056       8112 ... 1905282168 1905286224 1905290280]
CPU times: total: 31.2 ms
Wall time: 23.8 ms
[         0       4057       8114 ... 1915282165 1915286222 1915

[          0        4128        8256 ... -1669685344 -1669681216
 -1669677088]
CPU times: total: 31.2 ms
Wall time: 27.7 ms
[          0        4129        8258 ... -1659685347 -1659681218
 -1659677089]
CPU times: total: 15.6 ms
Wall time: 16.3 ms
[          0        4130        8260 ... -1649685350 -1649681220
 -1649677090]
CPU times: total: 15.6 ms
Wall time: 16 ms
[          0        4131        8262 ... -1639685353 -1639681222
 -1639677091]
CPU times: total: 15.6 ms
Wall time: 11.1 ms
[          0        4132        8264 ... -1629685356 -1629681224
 -1629677092]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        4133        8266 ... -1619685359 -1619681226
 -1619677093]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        4134        8268 ... -1609685362 -1609681228
 -1609677094]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[          0        4135        8270 ... -1599685365 -1599681230
 -1599677095]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         

[         0       4204       8408 ... -909685572 -909681368 -909677164]
CPU times: total: 15.6 ms
Wall time: 30.7 ms
[         0       4205       8410 ... -899685575 -899681370 -899677165]
CPU times: total: 0 ns
Wall time: 6.26 ms
[         0       4206       8412 ... -889685578 -889681372 -889677166]
CPU times: total: 15.6 ms
Wall time: 26.8 ms
[         0       4207       8414 ... -879685581 -879681374 -879677167]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       4208       8416 ... -869685584 -869681376 -869677168]
CPU times: total: 0 ns
Wall time: 5.27 ms
[         0       4209       8418 ... -859685587 -859681378 -859677169]
CPU times: total: 15.6 ms
Wall time: 27.7 ms
[         0       4210       8420 ... -849685590 -849681380 -849677170]
CPU times: total: 15.6 ms
Wall time: 17 ms
[         0       4211       8422 ... -839685593 -839681382 -839677171]
CPU times: total: 0 ns
Wall time: 4.03 ms
[         0       4212       8424 ... -829685596 -829681384 -829677172]
CPU t

[         0       4282       8564 ... -129685806 -129681524 -129677242]
CPU times: total: 46.9 ms
Wall time: 25.5 ms
[         0       4283       8566 ... -119685809 -119681526 -119677243]
CPU times: total: 15.6 ms
Wall time: 26.3 ms
[         0       4284       8568 ... -109685812 -109681528 -109677244]
CPU times: total: 15.6 ms
Wall time: 10.5 ms
[        0      4285      8570 ... -99685815 -99681530 -99677245]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      4286      8572 ... -89685818 -89681532 -89677246]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      4287      8574 ... -79685821 -79681534 -79677247]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      4288      8576 ... -69685824 -69681536 -69677248]
CPU times: total: 31.2 ms
Wall time: 31.2 ms
[        0      4289      8578 ... -59685827 -59681538 -59677249]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[        0      4290      8580 ... -49685830 -49681540 -49677250]
CPU times: total: 15.6 ms
Wa

[        0      4360      8720 ... 650313960 650318320 650322680]
CPU times: total: 31.2 ms
Wall time: 25.6 ms
[        0      4361      8722 ... 660313957 660318318 660322679]
CPU times: total: 15.6 ms
Wall time: 15.8 ms
[        0      4362      8724 ... 670313954 670318316 670322678]
CPU times: total: 15.6 ms
Wall time: 16.7 ms
[        0      4363      8726 ... 680313951 680318314 680322677]
CPU times: total: 15.6 ms
Wall time: 15 ms
[        0      4364      8728 ... 690313948 690318312 690322676]
CPU times: total: 15.6 ms
Wall time: 15 ms
[        0      4365      8730 ... 700313945 700318310 700322675]
CPU times: total: 0 ns
Wall time: 2.08 ms
[        0      4366      8732 ... 710313942 710318308 710322674]
CPU times: total: 31.2 ms
Wall time: 28.8 ms
[        0      4367      8734 ... 720313939 720318306 720322673]
CPU times: total: 15.6 ms
Wall time: 18.9 ms
[        0      4368      8736 ... 730313936 730318304 730322672]
CPU times: total: 31.2 ms
Wall time: 17 ms
[        0

[         0       4442       8884 ... 1470313714 1470318156 1470322598]
CPU times: total: 15.6 ms
Wall time: 21.2 ms
[         0       4443       8886 ... 1480313711 1480318154 1480322597]
CPU times: total: 0 ns
Wall time: 12.9 ms
[         0       4444       8888 ... 1490313708 1490318152 1490322596]
CPU times: total: 31.2 ms
Wall time: 21.4 ms
[         0       4445       8890 ... 1500313705 1500318150 1500322595]
CPU times: total: 15.6 ms
Wall time: 16 ms
[         0       4446       8892 ... 1510313702 1510318148 1510322594]
CPU times: total: 15.6 ms
Wall time: 13 ms
[         0       4447       8894 ... 1520313699 1520318146 1520322593]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       4448       8896 ... 1530313696 1530318144 1530322592]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       4449       8898 ... 1540313693 1540318142 1540322591]
CPU times: total: 15.6 ms
Wall time: 15.6 ms
[         0       4450       8900 ... 1550313690 1550318140 1550322590]

[          0        4516        9032 ... -2084653804 -2084649288
 -2084644772]
CPU times: total: 15.6 ms
Wall time: 19.6 ms
[          0        4517        9034 ... -2074653807 -2074649290
 -2074644773]
CPU times: total: 31.2 ms
Wall time: 31.5 ms
[          0        4518        9036 ... -2064653810 -2064649292
 -2064644774]
CPU times: total: 15.6 ms
Wall time: 16.7 ms
[          0        4519        9038 ... -2054653813 -2054649294
 -2054644775]
CPU times: total: 15.6 ms
Wall time: 20 ms
[          0        4520        9040 ... -2044653816 -2044649296
 -2044644776]
CPU times: total: 0 ns
Wall time: 34.2 ms
[          0        4521        9042 ... -2034653819 -2034649298
 -2034644777]
CPU times: total: 0 ns
Wall time: 32.5 ms
[          0        4522        9044 ... -2024653822 -2024649300
 -2024644778]
CPU times: total: 0 ns
Wall time: 31.8 ms
[          0        4523        9046 ... -2014653825 -2014649302
 -2014644779]
CPU times: total: 15.6 ms
Wall time: 28.2 ms
[          0       

In [2]:
import numpy as np
numpy_array = np.arange(1000000) # An array from 0 to 1000000

In [3]:
%time for i in range(100): result = numpy_array * 5

CPU times: total: 172 ms
Wall time: 186 ms


In [7]:
for i in range(100):
    result=numpy_array*100000000000000
%time result    

CPU times: total: 0 ns
Wall time: 0 ns


array([                  0,     100000000000000,     200000000000000, ...,
       7765979631452241920, 7766079631452241920, 7766179631452241920],
      dtype=int64)