In [1]:
import numpy as np

In [4]:
#Vectorization

In [2]:
arr = np.zeros((2,10))

In [6]:
arr+10 #10 is scalar

array([[10., 10., 10., 10., 10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10., 10., 10., 10., 10.]])

In [10]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
arr2 = np.ones((2,10))

In [11]:
arr2

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
arr+arr2 #Both operands are arrays

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
l1 = [1,2,4,5]
l2 = [3,4,6,7]

In [13]:
#Adding two list
sum = []
for i,_ in enumerate(l1): #0,1 1,2 2,4 3,5
    sum.append(l1[i] + l2[i])
print(sum)

[4, 6, 10, 12]


In [14]:
#where

In [15]:
marks = np.array([75,39,50, 80,90])

In [18]:
x = np.where(marks>=50,"Pass", "Fail")

In [19]:
x

array(['Pass', 'Fail', 'Pass', 'Pass', 'Pass'], dtype='<U4')

In [20]:
salary = np.array([10,70, 80, 50, 30])

In [22]:
incremented_salary = np.where(salary<50, salary*1.1, salary*1.05)

In [24]:
incremented_salary.dtype

dtype('float64')

In [26]:
arr = np.arange(1,101).reshape((10,10))

In [27]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [28]:
arr.T

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [29]:
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [30]:
arr.transpose()

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [31]:
arr = np.array([1,3,4,5,2])

In [32]:
arr.mean()

3.0

In [33]:
arr.cumsum()

array([ 1,  4,  8, 13, 15], dtype=int32)

In [34]:
arr.cumprod()

array([  1,   3,  12,  60, 120], dtype=int32)

In [ ]:
#Procedure Vs. Function
#Procedure doesn't return any value
#Function returns a value

In [35]:
#Methods for boolean arrays

In [36]:
gender = np.array(['Male', 'Female', 'Male', 'Male', 'Male'])

In [41]:
arr = gender == 'Male'
arr

array([ True, False,  True,  True,  True])

In [40]:
arr.sum()

4

In [42]:
arr = gender == 'Female'
arr.sum()

1

In [43]:
arr

array([False,  True, False, False, False])

In [44]:
arr.any()

True

In [45]:
arr.all()

False

In [46]:
arr = np.array([2,4,10,20,16])

In [50]:
x = (arr%2 == 0)

In [48]:
x

array([ True,  True,  True,  True,  True])

In [49]:
x.all()

True

In [ ]:
#Universal quantifier
#Existential quantifier

In [51]:
arr

array([ 2,  4, 10, 20, 16])

In [52]:
arr.sort()

In [53]:
arr

array([ 2,  4, 10, 16, 20])

In [55]:
arr.sort() #Inplace

In [56]:
arr[::-1]

array([20, 16, 10,  4,  2])

In [57]:
arr = np.array([1,2,4,1,6,2])

In [59]:
u = np.unique(arr)

In [61]:
#Save array

In [60]:
np.save('data',u)

In [62]:
#Load array

In [64]:
content = np.load('data.npy')

In [65]:
content

array([1, 2, 4, 6])

In [66]:
#Saving multiple arrays

In [67]:
students = np.array(["Ali","Asad","Ahmed"])
marks = np.array([30,20,60])

In [68]:
np.savez('arrays',std=students,m=marks)

In [74]:
results = np.load('arrays.npz')

In [75]:
results['std']

array(['Ali', 'Asad', 'Ahmed'], dtype='<U5')

In [77]:
results['m']

array([30, 20, 60])

In [78]:
arr=np.arange(16).reshape((4,4))

In [79]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [81]:
arr.diagonal()

array([ 0,  5, 10, 15])

In [82]:
arr.trace()

30

In [83]:
arr1=np.arange(10,26).reshape((4,4))

In [84]:
arr.dot(arr1)

array([[ 116,  122,  128,  134],
       [ 372,  394,  416,  438],
       [ 628,  666,  704,  742],
       [ 884,  938,  992, 1046]])

In [88]:
from numpy import linalg

In [89]:
linalg.det(arr)

0.0

In [91]:
linalg.eig(arr)

(array([ 3.24642492e+01, -2.46424920e+00,  2.14966418e-15, -1.17200157e-16]),
 array([[-0.11417645,  0.7327781 , -0.40377562,  0.05533605],
        [-0.3300046 ,  0.28974835,  0.81421492,  0.33237807],
        [-0.54583275, -0.15328139, -0.41710299, -0.83076428],
        [-0.76166089, -0.59631113,  0.00666369,  0.44305017]]))

In [94]:
linalg.inv(np.array([[1,5],[9,8]]))

array([[-0.21621622,  0.13513514],
       [ 0.24324324, -0.02702703]])

In [95]:
linalg.qr(arr)

(array([[ 0.        , -0.83666003,  0.54061686,  0.08793982],
        [-0.26726124, -0.47809144, -0.78636895,  0.28569892],
        [-0.53452248, -0.11952286, -0.04911268, -0.8352173 ],
        [-0.80178373,  0.23904572,  0.29486477,  0.46157856]]),
 array([[-1.49666295e+01, -1.65701970e+01, -1.81737645e+01,
         -1.97773319e+01],
        [ 0.00000000e+00, -1.19522861e+00, -2.39045722e+00,
         -3.58568583e+00],
        [ 0.00000000e+00,  0.00000000e+00, -3.82019983e-15,
         -4.31063089e-15],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,
          7.74364831e-17]]))

In [96]:
linalg.svd(arr)

(array([[-0.09184212, -0.83160389,  0.53515573,  0.11665482],
        [-0.31812733, -0.44586433, -0.80049034,  0.24334177],
        [-0.54441254, -0.06012478, -0.00448651, -0.836648  ],
        [-0.77069775,  0.32561478,  0.26982112,  0.47665141]]),
 array([3.51399637e+01, 2.27661021e+00, 1.69970911e-15, 8.07447880e-17]),
 array([[-0.42334086, -0.47243254, -0.52152422, -0.57061589],
        [ 0.72165263,  0.27714165, -0.16736932, -0.6118803 ],
        [-0.22125808,  0.66846675, -0.67315927,  0.2259506 ],
        [ 0.50104377, -0.50314233, -0.49684666,  0.49894522]]))

In [97]:
np.random.normal(3,4,(3,3))

array([[ 0.43606583,  4.27203603, -1.85127604],
       [-1.46327196,  1.86373419,  9.48334897],
       [ 3.11570102,  1.04362901,  6.9876883 ]])

In [99]:
np.random.gamma(1,2,(4,4))

array([[3.06371388, 1.86591286, 2.58023061, 0.89127798],
       [2.84303265, 5.33219431, 4.33796096, 1.42668399],
       [4.55751492, 0.98769555, 0.61390022, 1.73705547],
       [0.43125193, 5.56393488, 0.24515717, 0.50041773]])

In [106]:
np.random.seed(5)

In [107]:
np.random.rand()

0.22199317108973948

In [108]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
arr.reshape((2,2,4))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [119]:
arr = np.arange(16)

In [120]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [121]:
arr.reshape((4,4),order='F') #column major order

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [122]:
arr.reshape((4,4),order='C') #row major order

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [123]:
arr = np.array([[1,8,7],[3,4,5],[9,0,1]])

In [124]:
arr

array([[1, 8, 7],
       [3, 4, 5],
       [9, 0, 1]])

In [125]:
arr.flatten()

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [126]:
arr.ravel()

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [130]:
arr.reshape(9)

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [131]:
#Assignment: Difference between ravel and flatten

In [132]:
#Concatenate

In [133]:
a = np.array([[1,2],[3,4]])
b = np.array([[7,8],[9,10]])

In [136]:
print('a=',a)
print('b=',b)

a= [[1 2]
 [3 4]]
b= [[ 7  8]
 [ 9 10]]


In [137]:
np.concatenate((a,b),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10]])

In [138]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])

In [139]:
a = np.array([[1,7,9],[2,3,4],[5,6,7]])
b = np.array([[9,4,9],[2,3,2],[0,6,7]])

In [141]:
np.concatenate((a,b))

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [143]:
np.hstack((a,b)) #concatenate axis = 1

array([[1, 7, 9, 9, 4, 9],
       [2, 3, 4, 2, 3, 2],
       [5, 6, 7, 0, 6, 7]])

In [144]:
np.vstack((a,b)) #concatenate axis = 0

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [147]:
np.r_[a,b] #concatenate axis = 0

array([[1, 7, 9],
       [2, 3, 4],
       [5, 6, 7],
       [9, 4, 9],
       [2, 3, 2],
       [0, 6, 7]])

In [148]:
np.c_[a,b] #concatenate axis = 1

array([[1, 7, 9, 9, 4, 9],
       [2, 3, 4, 2, 3, 2],
       [5, 6, 7, 0, 6, 7]])

In [149]:
x = np.array([1,9,9,7,1,2,3])

In [153]:
np.split(x,[3, 5])

[array([1, 9, 9]), array([7, 1]), array([2, 3])]

In [164]:
l = np.arange(2,7,2)

In [165]:
l

array([2, 4, 6])

In [166]:
x

array([1, 9, 9, 7, 1, 2, 3])

In [167]:
np.split(x,l)

[array([1, 9]), array([9, 7]), array([1, 2]), array([3])]

In [168]:
x = np.array([[1,3],[2,4]])

In [170]:
x

array([[1, 3],
       [2, 4]])

In [169]:
np.split(x,[1])

[array([[1, 3]]), array([[2, 4]])]